export const theme = {
  colors: {
    'yellow': '#DBAC2C',
    'yellow-dark': '#C47F17',
    'yellow-light': '#F1E9C9',
    'purple': '#8047F8',
    'purple-dark': '#4B2995',
    'purple-light': '#EBE5F9',
    'base-title': '#272221',
    'base-subtitle': '#403937',
    'base-text': '#574F4D',
    'base-label': '#8D8686 ',
    'base-hover': '#D7D5D5',
    'base-button': '#E6E5E5',
    'base-input': '#EDEDED',
    'base-card': '#F3F2F2',
    'base-background': '#FAFAFA',
    'base-white': '#FFFFFF'
  },
  fontSizes: {
    'title-xl': '3rem',
    'title-l': '2rem',
    'title-m': '1.5rem',
    'title-s': '1.2rem',
    'title-xs': '1.125rem',
    'text-l': '1.25rem',
    'text-m': '1rem',
    'text-s': '0.875rem',
    'text-sm': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}